apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: smart-hostel

  labels:
    app: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: smarthostel-backend:local
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: smart-hostel-config

            - secretRef:
                name: smart-hostel-secret

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
