apiVersion: v1
kind: Secret

metadata:
  name: smart-hostel-secret
  namespace: smart-hostel

type: Opaque

stringData:
  DATABASE_URL: "postgresql://smarthostel:smarthostel_secret@postgres:5432/smarthosteldb"
  JWT_SECRET: "SmartHostelProductionSecretKey2026@123456789"
  GEMINI_API_KEY: ""
