apiVersion: apps/v1

kind: Deployment

metadata:
  name: smarthostel-backend

  labels:
    app: smarthostel-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: smarthostel-backend

  template:
    metadata:
      labels:
        app: smarthostel-backend

    spec:
      containers:

        - name: backend

          image: docker.io/library/smarthostel-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 3001

          envFrom:
            - configMapRef:
                name: smarthostel-backend-config

            - secretRef:
                name: smarthostel-backend-secret

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"
