apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: smart-hostel
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: smarthostel-backend:local
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: smart-hostel-config
        - secretRef:
            name: smart-hostel-secret
        command:
        - sh
        - -c
        - |
          npx prisma migrate deploy
          npx prisma db seed
