apiVersion: apps/v1

kind: Deployment

metadata:
  name: smarthostel-frontend

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: smarthostel-frontend

  template:
    metadata:
      labels:
        app: smarthostel-frontend

    spec:
      containers:

        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          ports:
            - containerPort: {{ .Values.frontend.service.port }}
