apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: smart-hostel

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres

          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: smarthostel

            - name: POSTGRES_PASSWORD
              value: smarthostel_secret

            - name: POSTGRES_DB
              value: smarthosteldb

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
